appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: a0pw3fvFocYskastkY/JCV/l3LD6tiQ9pPEWMmaX1Dje+uHJ+Mf8njBeVcj0fca9Wlg88SpnLHOnyw0SP3PgHDgijps0/vYo7o3b6O24XHvDIWiGFxg9hugD9VwyC1HtSGoEamif61XRBdpyj8xP9q71luW6E5q3haxoSIOB7AOlD91UFBRmYUovhdPWy1iIGlQRHnCJKhgSbe2y06P2VAsvVXcRlEDBIO61QZi9wJsf68oWSOlVbAbiHmXDPlORcsBsRt3EmuHmPGJKf/GUMOByy09GViMOr0/DRWJRQIW+s0cL+aLAiyShn2IpZe3odpkbBzqAlxyhf2WwinSy9LwC8xGFlPbbbBxE+16Pu7/CjWOKkl2flLp5NlOrkem0KcfjP+z6yDyQH1JgOe7Cv7kdE0+4jyHwmN3xx4zvFeXqyzYiQk79HIE+3aM0QL+S+tkYhqo+1fvJ37GyRiFw71S3cU1BXfBS8C8CTORLDUSk8MZFggsgOQ47x8cpX3SUy1SPXlXCAWk4Qm45f05WBDZcjYqw38LpOuYdRsvGRB92YiTlCM+vSYyNJLqrWAobgSj/TDozC/8LehncK5+5B16XRwVoMn6x86N//S0B+fAW1IjYnPg2c/UOMrnypbl9JplGCXyGgb1ZTVLLWbadPo5yL/inejq/7cv3YaGuwO4=}
bot:
  automerge: true
